import {
  SquareTerminal,
  TrendingUp,
  Network,
  MessageSquare,
  Rocket,
  Target, LayoutDashboard, CircleDollarSign, Users, ChartCandlestick, Telescope, MessagesSquare
} from "lucide-react"

export const DEFAULT_SKILLS = [
  "LinkedIn Portfolio",
  "Web Development",
  "Design",
  "Marketing",
  "Data Analysis",
  "JavaScript",
  "React",
  "Node.js",
  "Python",
  "UI/UX Design",
  "Project Management",
  "Digital Marketing",
  "SEO",
  "Content Writing",
  "Graphic Design",
  "TypeScript",
  "Vue.js",
  "Angular",
  "PHP",
  "Java",
  "C++",
  "Mobile Development",
  "DevOps",
  "Cloud Computing",
  "Machine Learning",
  "Artificial Intelligence",
  "Cybersecurity",
  "Database Management",
  "Product Management",
  "Sales",
  "Customer Service",
  "Business Analysis",
  "Consulting",
  "Photography",
  "Video Editing",
  "Social Media Management",
  "Email Marketing",
  "Brand Management",
  "Public Relations",
]

export const DEFAULT_LOCATIONS = [
  "Australia - Brisbane, QLD",
  "Australia - Gold Coast, QLD",
  "Australia - Melbourne, VIC",
  "Australia - Newcastle, NSW",
  "Australia - Sydney, NSW",
  "Belgium - Antwerp",
  "Belgium - Brussels",
  "Canada - Halifax, NS",
  "Canada - Kitchener, ON",
  "Canada - London, ON",
  "Canada - Montreal, QC",
  "Canada - Toronto, ON",
  "Canada - Vancouver, BC",
  "Canada - Victoria, BC",
  "Denmark - Aarhus",
  "Denmark - Copenhagen",
  "Denmark - Odense",
  "Ethiopia - Adama",
  "Ethiopia - Addis Ababa",
  "Ethiopia - Bahir Dar",
  "Ethiopia - Dessie",
  "Ethiopia - Dire Dawa",
  "Ethiopia - Gondar",
  "Ethiopia - Hawassa",
  "Ethiopia - Jimma",
  "Ethiopia - Mekelle",
  "Finland - Espoo",
  "Finland - Helsinki",
  "Finland - Tampere",
  "France - Aix-en-Provence",
  "France - Bordeaux",
  "France - Lille",
  "France - Lyon",
  "France - Marseille",
  "France - Montpellier",
  "France - Nantes",
  "France - Nice",
  "France - Paris",
  "France - Reims",
  "France - Rennes",
  "France - Saint-Étienne",
  "France - Strasbourg",
  "Germany - Berlin",
  "Germany - Bremen",
  "Germany - Cologne",
  "Germany - Dortmund",
  "Germany - Dresden",
  "Germany - Frankfurt am Main",
  "Germany - Hamburg",
  "Germany - Hanover",
  "Germany - Leipzig",
  "Germany - Munich",
  "Germany - Nuremberg",
  "Germany - Stuttgart",
  "Ireland - Cork",
  "Ireland - Dublin",
  "Italy - Bari",
  "Italy - Bologna",
  "Italy - Florence",
  "Italy - Genoa",
  "Italy - Milan",
  "Italy - Naples",
  "Italy - Rome",
  "Italy - Turin",
  "Japan - Hiroshima",
  "Japan - Kyoto",
  "Japan - Tokyo",
  "Japan - Yokohama",
  "Netherlands - Amsterdam",
  "Netherlands - Eindhoven",
  "Netherlands - Rotterdam",
  "Netherlands - The Hague",
  "Netherlands - Utrecht",
  "Norway - Bergen",
  "Norway - Oslo",
  "Portugal - Lisbon",
  "Portugal - Porto",
  "Singapore - Singapore",
  "Spain - Barcelona",
  "Spain - Bilbao",
  "Spain - Madrid",
  "Sweden - Gothenburg",
  "Sweden - Malmö",
  "Sweden - Stockholm",
  "Sweden - Uppsala",
  "Switzerland - Basel",
  "Switzerland - Geneva",
  "Switzerland - Zurich",
  "United Kingdom - Birmingham",
  "United Kingdom - Glasgow",
  "United Kingdom - Leeds",
  "United Kingdom - Liverpool",
  "United Kingdom - London",
  "United Kingdom - Manchester",
  "United States - Chicago, IL",
  "United States - Colorado Springs, CO",
  "United States - Houston, TX",
  "United States - Las Vegas, NV",
  "United States - Los Angeles, CA",
  "United States - Louisville, KY",
  "United States - Memphis, TN",
  "United States - Miami, FL",
  "United States - New York, NY",
  "United States - Omaha, NE",
  "United States - Philadelphia, PA",
  "United States - Phoenix, AZ",
  "United States - Portland, OR",
  "United States - Raleigh, NC",
  "United States - San Jose, CA",
  "Remote"
];


export interface FormData {
  // Step 1: Brand Basics
  logo: string | null
  startupName: string
  tagline: string
  location: string
  website: string

  // Step 2: What You're Building
  productStage: string
  fundingRoundType: string
  startupDescription: string
  totalRaised: string
  additionalInfo: string
}

export const INITIAL_PROFILE_DATA = {
  fullName: "Feven Teaf",
  bio: "",
  skills: ["LinkedIn Portfolio"],
  address: "",
  avatar: null,
}

export const INITIAL_EMAIL_ADDRESSES = [
  {
    id: "1",
    email: "feventeaf322@gmail.com",
    addedDate: "1 month ago",
  },
]

export const INITIAL_FORM_DATA: FormData = {
  logo: null,
  startupName: "",
  tagline: "",
  location: "",
  website: "",
  productStage: "",
  fundingRoundType: "",
  startupDescription: "",
  totalRaised: "",
  additionalInfo: "",
}

export const PRODUCT_STAGES = [
  "💡 Idea",
  "🚀 MVP",
  "🧪 Beta",
  "📢 Launch",
  "📈 Growth",
  "🌍 Scale"
];

export const FUNDING_ROUNDS = [
  "🌱 Pre-seed",
  "🌿 Seed",
  "💰 Series A",
  "💵 Series B",
  "🏦 Series C+",
  "🚫 Not fundraising"
];

export const FEATURES = [
  {
    title: "🔍 AI-Powered Investment Insights",
    description: "Utilize advanced sentiment analysis to make data-driven decisions for your startup.",
    linkText: "Learn More"
  },
  {
    title: "🤝 Matchmaking That Matters",
    description: "Launch and manage campaigns seamlessly, connecting with investors worldwide.",
    linkText: "Learn More"
  },
  {
    title: "🚀 Accelerate Startup Growth",
    description: "Find the perfect investors or startups effortlessly with our AI-driven matchmaking tools.",
    linkText: "Learn More"
  },
  {
    title: "🌐 A Hub for Collaboration",
    description: "Collaborate in real-time with like-minded entrepreneurs and investors.",
    linkText: "Learn More"
  }
];

export const EntrepreneurNavMain = [
  {
    title: "Dashboard",
    url: "/entrepreneur/dashboard",
    icon: SquareTerminal,
    id: "dashboard",
  },
  {
    title: "Startups",
    url: "/entrepreneur/my-startups",
    icon: Rocket,
    id: "startups",
    items: [
      {
        title: "My Startups",
        url: "/entrepreneur/my-startups",
        id: "my-startups",
      },
      {
        title: "Saved Startups",
        url: "/entrepreneur/saved-startups",
        id: "saved-startups",
      },
    ],
  },
  {
    title: "Crowdfunding",
    url: "/entrepreneur/my-campaigns",
    icon: Target,
    id: "crowdfunding",
    items: [
      {
        title: "My Campaigns",
        url: "/entrepreneur/my-campaigns",
        id: "my-campaigns",
      },
      {
        title: "Funded Campaigns",
        url: "/entrepreneur/funded-campaigns",
        id: "funded-campaigns",
      },
      {
        title: "Explore Campaigns",
        url: "/entrepreneur/explore-campaigns",
        id: "explore-campaigns",
      },
    ],
  },
  {
    title: "Market Insights",
    url: "/entrepreneur/market-insights",
    icon: TrendingUp,
    id: "market-insights",
  },
  {
    title: "Network",
    url: "/entrepreneur/network",
    icon: Network,
    id: "network",
  },
  {
    title: "Collab Space",
    url: "/entrepreneur/collab-space",
    icon: MessageSquare,
    id: "collab-space",
  },
]

export const InvestorNavMain = [
  {
    title: "Dashboard",
    url: "/investor/dashboard",
    icon: LayoutDashboard,
    id: "dashboard",
  },
  {
    title: "My Investments",
    url: "/investor/invested",
    icon: CircleDollarSign,
    id: "my-investments",
    items: [
      {
        title: "Invested Startups",
        url: "/investor/invested-startups",
        id: "invested-startups",
      },
      {
        title: "Funded Campaigns",
        url: "/investor/funded-campaigns",
        id: "funded-campaigns",
      },
    ],
  },
  {
    title: "Explore",
    url: "/investor/startups",
    icon: Telescope,
    id: "explore",
    items: [
      {
        title: "All Startups",
        url: "/investor/startups",
        id: "all-startups",
      },
      {
        title: "Saved Startups",
        url: "/investor/saved-startups",
        id: "saved-startups",
      },
      {
        title: "Campaigns",
        url: "/investor/campaigns",
        id: "campaigns",
      },
    ],
  },
  {
    title: "Market Insights",
    url: "/investor/market-insights",
    icon: ChartCandlestick,
    id: "market-insights",
  },
  {
    title: "Network",
    url: "/investor/network",
    icon: Users,
    id: "network",
  },
  {
    title: "Collab Space",
    url: "/investor/collab-space",
    icon: MessagesSquare,
    id: "collab-space",
  },
];

export const TRENDING_PROJECTS = [
  {
    image: "/images/eco.jpg",
    title: "AI-Powered Investment Insights",
    tagline: "Revolutionizing investment strategies through AI.",
    currentStage: "Growth",
    industries: ["Agriculture", "Tech", "Industry"],
    funding: "$2.4M",
    target: "$3M",
    progress: 80,
    link: "#",
  },
  {
    image: "/images/ai-health.jpg",
    title: "AI-Driven Healthcare Solutions",
    tagline: "Transforming patient care with predictive analytics.",
    currentStage: "Seed",
    industries: ["Healthcare", "Biotech"],
    funding: "$1.1M",
    target: "$5M",
    progress: 22,
    link: "#",
  },
  {
    image: "/images/renew.jpg",
    title: "Retail AI Optimization",
    tagline: "Enhancing customer experiences through AI.",
    currentStage: "Series A",
    industries: ["Retail", "E-commerce"],
    funding: "$3M",
    target: "$10M",
    progress: 30,
    link: "#",
  },
  {
    image: "/images/eco.jpg",
    title: "Smart Energy Management",
    tagline: "Optimizing energy consumption with AI technologies.",
    currentStage: "Prototype",
    industries: ["Energy", "Tech"],
    funding: "$500K",
    target: "$1M",
    progress: 50,
    link: "#",
  },
  {
    image: "/images/ai-health.jpg",
    title: "AI in Education",
    tagline: "Personalizing learning experiences for students worldwide.",
    currentStage: "Scale",
    industries: ["Education", "EdTech"],
    funding: "$4M",
    target: "$6M",
    progress: 67,
    link: "#",
  },
  {
    image: "/images/eco.jpg",
    title: "Financial Fraud Detection",
    tagline: "Securing financial systems through advanced AI detection.",
    currentStage: "Beta Testing",
    industries: ["Finance", "Cybersecurity"],
    funding: "$3.5M",
    target: "$5M",
    progress: 70,
    link: "#",
  },
  {
    image: "/images/renew.jpg",
    title: "Autonomous Logistics Optimization",
    tagline: "Streamlining supply chains with AI automation.",
    currentStage: "Pilot",
    industries: ["Transportation", "Logistics"],
    funding: "$1.8M",
    target: "$4M",
    progress: 45,
    link: "#",
  },
];

// Mock data for trending projects
// export const TRENDING_PROJECTS = [
//   {
//     id: 1,
//     name: "EcoTech Solutions",
//     category: "Green Technology",
//     funding: "$2.4M",
//     target: "$3M",
//     progress: 80,
//     investors: 1247,
//     timeLeft: "12 days",
//     image: "/images/eco.jpg",
//     growth: "+24%",
//     link: "#",
//   },
//   {
//     id: 2,
//     name: "AI Healthcare Platform",
//     category: "Healthcare",
//     funding: "$1.8M",
//     target: "$2.5M",
//     progress: 72,
//     investors: 892,
//     timeLeft: "8 days",
//     image: "/images/ai-health.jpg",
//     growth: "+18%",
//     link: "#",
//   },
//   {
//     id: 3,
//     name: "Blockchain Finance",
//     category: "Fintech",
//     funding: "$3.2M",
//     target: "$4M",
//     progress: 85,
//     investors: 1567,
//     timeLeft: "15 days",
//     image: "/images/blockchain.jpg",
//     growth: "+32%",
//     link: "#",
//   },
//   {
//     id: 4,
//     name: "Smart City IoT",
//     category: "Technology",
//     funding: "$1.5M",
//     target: "$2M",
//     progress: 75,
//     investors: 743,
//     timeLeft: "20 days",
//     image: "/images/smart-iot.png",
//     growth: "+15%",
//     link: "#",
//   },
//   {
//     id: 5,
//     name: "Renewable Energy",
//     category: "Energy",
//     funding: "$4.1M",
//     target: "$5M",
//     progress: 82,
//     investors: 2134,
//     timeLeft: "5 days",
//     image: "/images/renew.jpg",
//     growth: "+28%",
//     link: "#",
//   },
// ]

// Mock data for projects grid
export const PROJECTS_GRID = [
  {
    id: "1",
    name: "EcoTech Solutions",
    category: "CleanTech",
    image: "/images/eco.jpg",
    funding: "$2.4M",
    status: "In Progress",
    progress: 75,
    industries: ["Renewable Energy", "Sustainability"],
    founderName: "Alex Rivera",
    avatar: "/images/Portfolio2.png",
    rating: 4.8,
  },
  {
    id: "2",
    name: "MediHealth AI",
    category: "HealthTech",
    image: "/images/ai-health.jpg",
    funding: "$1.8M",
    status: "Completed",
    progress: 100,
    industries: ["Healthcare", "AI", "Analytics"],
    founderName: "Sarah Chen",
    avatar: "/images/Portfolio1.png",
    rating: 5.0,
  },
  {
    id: "3",
    name: "FinEdge",
    category: "FinTech",
    image: "/images/Portfolio3.png",
    funding: "$3.2M",
    status: "In Progress",
    progress: 60,
    industries: ["Finance", "Blockchain"],
    founderName: "Michael Johnson",
    avatar: "/images/Portfolio1.png",
    rating: 4.5,
  },
  {
    id: "4",
    name: "EduLearn Platform",
    category: "EdTech",
    image: "/images/renew.jpg",
    funding: "$1.5M",
    status: "New",
    progress: 30,
    industries: ["Education", "SaaS"],
    founderName: "Priya Patel",
    avatar: "/images/Portfolio22.png",
    rating: 4.2,
  },
  {
    id: "5",
    name: "AgriSmart",
    category: "AgTech",
    image: "/images/smart-iot.png",
    funding: "$2.1M",
    status: "In Progress",
    progress: 65,
    industries: ["Agriculture", "IoT"],
    founderName: "Carlos Rodriguez",
    avatar: "/images/Portfolio3.png",
    rating: 4.7,
  },
  {
    id: "6",
    name: "RetailAI",
    category: "Retail",
    image: "/images/eco.jpg",
    funding: "$1.9M",
    status: "New",
    progress: 25,
    industries: ["Retail", "AI", "Analytics"],
    founderName: "Emma Wilson",
    avatar: "/images/Portfolio1.png",
    rating: 4.3,
  },
]


// Mock data for startups
export const STARTUPS = [
  {
    id: 1,
    name: "Coinbase",
    tagline: "Cryptocurrency Exchange",
    amount: "$15,000",
    image: "/images/eco.jpg",
    stage: "Profitable",
    saved: 3,
    industry: ["ai-tech", "bee-farm", "call-away"]
  },
  {
    id: 2,
    name: "Tesla Motors",
    tagline: "Electric Vehicles",
    amount: "$12,500",
    image: "/images/eco.jpg",
    stage: "Profitable",
    saved: 3,
    industry: ["ai-tech", "bee-farm", "call-away"]
  },
  {
    id: 3,
    name: "Meta Platforms",
    tagline: "Social Media",
    amount: "$8,750",
    image: "/images/eco.jpg",
    stage: "Profitable",
    saved: 3,
    industry: ["ai-tech", "bee-farm", "call-away"]
  },
  {
    id: 4,
    name: "Amazon",
    tagline: "E-commerce",
    amount: "$20,000",
    image: "/images/eco.jpg",
    stage: "Profitable",
    saved: 3,
    industry: ["ai-tech", "bee-farm", "call-away"]
  },
]

// Mock data for investments
export const INVESTMENTS = [
  {
    id: 1,
    name: "Coinbase",
    type: "Cryptocurrency Exchange",
    amount: "$15,000",
    returns: "+$3,250",
    percentage: "+21.67%",
    image: "/images/eco.jpg",
    status: "Profitable",
  },
  {
    id: 2,
    name: "Tesla Motors",
    type: "Electric Vehicles",
    amount: "$12,500",
    returns: "+$2,890",
    percentage: "+23.12%",
    image: "/images/eco.jpg",
    status: "Profitable",
  },
  {
    id: 3,
    name: "Meta Platforms",
    type: "Social Media",
    amount: "$8,750",
    returns: "+$1,456",
    percentage: "+16.64%",
    image: "/images/eco.jpg",
    status: "Profitable",
  },
  {
    id: 4,
    name: "Amazon",
    type: "E-commerce",
    amount: "$20,000",
    returns: "+$4,200",
    percentage: "+21.00%",
    image: "/images/eco.jpg",
    status: "Profitable",
  },
]

// Mock data for Rising Projects chart
export const RISING_PROJECTS_DATA = [
  {
    month: "Jan",
    MVP: 4,
    Seed: 3,
    Final: 2,
  },
  {
    month: "Feb",
    MVP: 3,
    Seed: 2,
    Final: 2,
  },
  {
    month: "Mar",
    MVP: 2,
    Seed: 2,
    Final: 3,
  },
  {
    month: "Apr",
    MVP: 3,
    Seed: 4,
    Final: 2,
  },
  {
    month: "May",
    MVP: 2,
    Seed: 5,
    Final: 2,
  },
  {
    month: "Jun",
    MVP: 2,
    Seed: 3,
    Final: 3,
  },
  {
    month: "Jul",
    MVP: 3,
    Seed: 4,
    Final: 3,
  },
]

// Mock data for Your Spending chart
export const SPENDING_DATA = [
  {
    month: "Jan",
    amount: 3200,
  },
  {
    month: "Feb",
    amount: 4100,
  },
  {
    month: "Mar",
    amount: 2800,
  },
  {
    month: "Apr",
    amount: 3600,
  },
  {
    month: "May",
    amount: 2900,
  },
  {
    month: "Jun",
    amount: 3700,
  },
  {
    month: "Jul",
    amount: 3300,
  },
  {
    month: "Aug",
    amount: 4800,
  },
]

// Define types for our stats data
export interface StatCard {
  id: string
  title: string
  value: string | number
  change: {
    value: string
    trend: "up" | "down" | "neutral"
    text: string
  }
  icon: "dollar" | "trending" | "star"
  link: string
  rating?: number // Only used for rating card
}

// Dummy data for demonstration
export const STAT_DATA: StatCard[] = [
  {
    id: "startups",
    title: "Total Startups",
    value: 300,
    change: {
      value: "+12%",
      trend: "up",
      text: "from last month",
    },
    icon: "dollar",
    link: "/startups",
  },
  {
    id: "earnings",
    title: "Total Earnings",
    value: "$5,000.00",
    change: {
      value: "+8%",
      trend: "up",
      text: "this quarter",
    },
    icon: "trending",
    link: "/earnings",
  },
  {
    id: "rating",
    title: "Rating",
    value: "3.5/5",
    change: {
      value: "",
      trend: "neutral",
      text: "",
    },
    icon: "star",
    link: "/ratings",
    rating: 3.5,
  },
]

import type { User } from "@/types/user";

export const sampleUsers: User[] = [
  {
    id: "1",
    name: "John Smith",
    photo: "/images/person1.jpg",
    rating: 4.8,
    badges: ["Tech", "Startup"],
    bio: "A passionate entrepreneur with experience in AI startups.",
    address: "San Francisco, CA",
    role: "Entrepreneur",
    startupCount: 1,
  },
  {
    id: "2",
    name: "Jane Doe",
    photo: "/images/person2.jpg",
    rating: 5.0,
    badges: ["Finance", "Investment"],
    bio: "Seasoned investor with a focus on green energy projects.",
    address: "New York, NY",
    role: "Investor",
    totalInvestment: "$38.9M",
  },
  {
    id: "3",
    name: "Michael Johnson",
    photo: "/images/person3.jpg",
    rating: 4.7,
    badges: ["AI/ML", "SaaS"],
    bio: "Tech entrepreneur focused on sustainable energy and climate solutions.",
    address: "Austin, TX",
    role: "Entrepreneur",
    startupCount: 1,
  },
  {
    id: "4",
    name: "Sarah Williams",
    photo: "/images/person4.jpg",
    rating: 4.9,
    badges: ["Venture Capital", "Strategic"],
    bio: "Venture capitalist specializing in early-stage technology companies.",
    address: "Seattle, WA",
    role: "Investor",
    totalInvestment: "$38.9M",
  },
  {
    id: "5",
    name: "Emily Brown",
    photo: "/images/person1.jpg",
    rating: 4.6,
    badges: ["E-commerce", "FinTech"],
    bio: "Innovative leader developing cutting-edge fintech platforms.",
    address: "Chicago, IL",
    role: "Entrepreneur",
    startupCount: 1,
  },
  {
    id: "6",
    name: "David Garcia",
    photo: "/images/person2.jpg",
    rating: 5.0,
    badges: ["Angel", "Healthcare"],
    bio: "Angel investor with expertise in healthcare and biotech startups.",
    address: "Boston, MA",
    role: "Investor",
    totalInvestment: "$38.9M",
  },
  {
    id: "7",
    name: "Jessica Taylor",
    photo: "/images/person3.jpg",
    rating: 4.8,
    badges: ["AR/VR", "Gaming"],
    bio: "Creative founder developing immersive AR/VR experiences.",
    address: "Los Angeles, CA",
    role: "Entrepreneur",
    startupCount: 1,
  },
  {
    id: "8",
    name: "William Lee",
    photo: "/images/person4.jpg",
    rating: 4.9,
    badges: ["Seed", "AI/ML"],
    bio: "Seed-stage investor with a thesis on AI and machine learning.",
    address: "Toronto, Canada",
    role: "Investor",
    totalInvestment: "$38.9M",
  },
  {
    id: "9",
    name: "Amanda Moore",
    photo: "/images/person1.jpg",
    rating: 4.7,
    badges: ["EdTech", "CleanTech"],
    bio: "Visionary founder transforming the education technology landscape.",
    address: "London, UK",
    role: "Entrepreneur",
    startupCount: 1,
  },
  {
    id: "10",
    name: "Christopher White",
    photo: "/images/person2.jpg",
    rating: 5.0,
    badges: ["Private Equity", "Portfolio"],
    bio: "Private equity investor focused on mature technology companies.",
    address: "Berlin, Germany",
    role: "Investor",
    totalInvestment: "$38.9M",
  },
  {
    id: "11",
    name: "Paul Martinez",
    photo: "/images/person3.jpg",
    rating: 4.5,
    badges: ["Healthcare", "Innovation"],
    bio: "Serial founder building innovative solutions for the healthcare industry.",
    address: "San Francisco, CA",
    role: "Entrepreneur",
    startupCount: 1,
  },
  {
    id: "12",
    name: "Rebecca Harris",
    photo: "/images/person4.jpg",
    rating: 4.9,
    badges: ["Venture Capital", "FinTech"],
    bio: "Corporate venture investor seeking innovative enterprise solutions.",
    address: "New York, NY",
    role: "Investor",
    totalInvestment: "$38.9M",
  },
  {
    id: "13",
    name: "Steven Brown",
    photo: "/images/person1.jpg",
    rating: 4.6,
    badges: ["Cybersecurity", "Engineering"],
    bio: "Cybersecurity expert building advanced threat protection systems.",
    address: "Boston, MA",
    role: "Entrepreneur",
    startupCount: 1,
  },
  {
    id: "14",
    name: "Heather Johnson",
    photo: "/images/person2.jpg",
    rating: 5.0,
    badges: ["Angel", "Enterprise"],
    bio: "Strategic advisor and investor in emerging technology trends.",
    address: "Austin, TX",
    role: "Investor",
    totalInvestment: "$38.9M",
  },
  {
    id: "15",
    name: "George Miller",
    photo: "/images/person3.jpg",
    rating: 4.7,
    badges: ["Gaming", "Mobile"],
    bio: "Gaming entrepreneur developing the next generation of interactive entertainment.",
    address: "Seattle, WA",
    role: "Entrepreneur",
    startupCount: 1,
  },
  {
    id: "16",
    name: "Catherine Wilson",
    photo: "/images/person4.jpg",
    rating: 4.9,
    badges: ["Growth", "CleanTech"],
    bio: "Impact investor supporting sustainable and social impact startups.",
    address: "Chicago, IL",
    role: "Investor",
    totalInvestment: "$38.9M",
  },
  {
    id: "17",
    name: "Brian Adams",
    photo: "/images/person1.jpg",
    rating: 4.6,
    badges: ["BioTech", "IoT"],
    bio: "Entrepreneur developing groundbreaking biotech solutions.",
    address: "Berlin, Germany",
    role: "Entrepreneur",
    startupCount: 1,
  },
  {
    id: "18",
    name: "Laura Scott",
    photo: "/images/person2.jpg",
    rating: 5.0,
    badges: ["Corporate", "Accelerator"],
    bio: "Accelerator partner helping startups scale and grow rapidly.",
    address: "Singapore",
    role: "Investor",
    totalInvestment: "$38.9M",
  },
  {
    id: "19",
    name: "Kimberly Green",
    photo: "/images/person3.jpg",
    rating: 4.7,
    badges: ["Product", "Data Science"],
    bio: "Product-focused entrepreneur creating next-generation mobile applications.",
    address: "Sydney, Australia",
    role: "Entrepreneur",
    startupCount: 1,
  },
  {
    id: "20",
    name: "Ryan Evans",
    photo: "/images/person4.jpg",
    rating: 4.9,
    badges: ["Family Office", "Consumer"],
    bio: "Family office investor with a focus on consumer technology.",
    address: "Tel Aviv, Israel",
    role: "Investor",
    totalInvestment: "$38.9M",
  },
  {
    id: "21",
    name: "Mark Rivera",
    photo: "/images/person1.jpg",
    rating: 4.5,
    badges: ["Gaming", "FinTech"],
    bio: "Entrepreneur crafting innovative financial gaming applications.",
    address: "Miami, FL",
    role: "Entrepreneur",
    startupCount: 1,
  },
  {
    id: "22",
    name: "Sandra Walker",
    photo: "/images/person2.jpg",
    rating: 5.0,
    badges: ["Series A", "Strategic"],
    bio: "Seasoned investor helping startups achieve growth and scale.",
    address: "Nashville, TN",
    role: "Investor",
    totalInvestment: "$38.9M",
  },
  {
    id: "23",
    name: "Edward Carter",
    photo: "/images/person3.jpg",
    rating: 4.8,
    badges: ["AR/VR", "Product"],
    bio: "Entrepreneur exploring cutting-edge AR/VR applications for retail.",
    address: "San Francisco, CA",
    role: "Entrepreneur",
    startupCount: 1,
  },
  {
    id: "24",
    name: "Maria Collins",
    photo: "/images/person4.jpg",
    rating: 4.7,
    badges: ["Growth", "FinTech"],
    bio: "Growth-stage investor with a focus on innovative payment solutions.",
    address: "Berlin, Germany",
    role: "Investor",
    totalInvestment: "$38.9M",
  },
  {
    id: "25",
    name: "Ronald Baker",
    photo: "/images/person1.jpg",
    rating: 4.6,
    badges: ["EdTech", "Innovation"],
    bio: "Founder committed to revolutionizing online education platforms.",
    address: "London, UK",
    role: "Entrepreneur",
    startupCount: 1,
  },
  {
    id: "26",
    name: "Helen Turner",
    photo: "/images/person2.jpg",
    rating: 4.9,
    badges: ["Angel", "CleanTech"],
    bio: "Angel investor passionate about supporting sustainable technologies.",
    address: "Amsterdam, Netherlands",
    role: "Investor",
    totalInvestment: "$38.9M",
  },
  {
    id: "27",
    name: "Jacob Phillips",
    photo: "/images/person3.jpg",
    rating: 4.5,
    badges: ["Cybersecurity", "Enterprise"],
    bio: "Entrepreneur building scalable enterprise-grade cybersecurity tools.",
    address: "New York, NY",
    role: "Entrepreneur",
    startupCount: 1,
  },
  {
    id: "28",
    name: "Rachel Reyes",
    photo: "/images/person4.jpg",
    rating: 5.0,
    badges: ["Due Diligence", "Portfolio"],
    bio: "Investor focused on robust portfolio management and due diligence.",
    address: "Singapore",
    role: "Investor",
    totalInvestment: "$38.9M",
  },
  {
    id: "29",
    name: "Timothy Nguyen",
    photo: "/images/person1.jpg",
    rating: 4.7,
    badges: ["AI/ML", "Engineering"],
    bio: "AI engineer creating innovative solutions for data-driven industries.",
    address: "Sydney, Australia",
    role: "Entrepreneur",
    startupCount: 1,
  },
  {
    id: "30",
    name: "Megan Parker",
    photo: "/images/person2.jpg",
    rating: 4.9,
    badges: ["Incubator", "Tech"],
    bio: "Incubator lead specializing in tech startups and innovation.",
    address: "Tel Aviv, Israel",
    role: "Investor",
    totalInvestment: "$38.9M",
  },
  {
    id: "31",
    name: "George Hill",
    photo: "/images/person3.jpg",
    rating: 4.8,
    badges: ["CleanTech", "AgTech"],
    bio: "Entrepreneur advancing agricultural technologies for sustainability.",
    address: "Miami, FL",
    role: "Entrepreneur",
    startupCount: 1,
  },
  {
    id: "32",
    name: "Elizabeth Diaz",
    photo: "/images/person4.jpg",
    rating: 5.0,
    badges: ["Private Equity", "Healthcare"],
    bio: "Private equity investor with a passion for health tech ventures.",
    address: "Nashville, TN",
    role: "Investor",
    totalInvestment: "$38.9M",
  },
  {
    id: "33",
    name: "Joshua Allen",
    photo: "/images/person1.jpg",
    rating: 4.6,
    badges: ["Web3", "Blockchain"],
    bio: "Blockchain entrepreneur creating decentralized financial ecosystems.",
    address: "San Francisco, CA",
    role: "Entrepreneur",
    startupCount: 1,
  },
  {
    id: "34",
    name: "Nicole Green",
    photo: "/images/person2.jpg",
    rating: 4.9,
    badges: ["Strategic", "Innovation"],
    bio: "Strategic investor with a focus on early-stage tech startups.",
    address: "Berlin, Germany",
    role: "Investor",
    totalInvestment: "$38.9M",
  },
  {
    id: "35",
    name: "Andrew Scott",
    photo: "/images/person3.jpg",
    rating: 4.7,
    badges: ["IoT", "CleanTech"],
    bio: "Entrepreneur leveraging IoT for sustainable city development.",
    address: "London, UK",
    role: "Entrepreneur",
    startupCount: 1,
  },
  {
    id: "36",
    name: "Sharon Baker",
    photo: "/images/person4.jpg",
    rating: 5.0,
    badges: ["Angel", "Growth"],
    bio: "Angel investor focused on scaling innovative startup solutions.",
    address: "Amsterdam, Netherlands",
    role: "Investor",
    totalInvestment: "$38.9M",
  },
  {
    id: "37",
    name: "Eric Thomas",
    photo: "/images/person1.jpg",
    rating: 4.8,
    badges: ["AI/ML", "Data Science"],
    bio: "AI entrepreneur specializing in advanced data analytics.",
    address: "Austin, TX",
    role: "Entrepreneur",
    startupCount: 1,
  },
  {
    id: "38",
    name: "Angela Ramirez",
    photo: "/images/person2.jpg",
    rating: 4.9,
    badges: ["Series B", "Healthcare"],
    bio: "Investor passionate about funding transformative healthcare solutions.",
    address: "Seattle, WA",
    role: "Investor",
    totalInvestment: "$38.9M",
  },
  {
    id: "39",
    name: "Michelle Taylor",
    photo: "/images/person3.jpg",
    rating: 4.6,
    badges: ["E-commerce", "B2B"],
    bio: "Entrepreneur revolutionizing online retail for businesses.",
    address: "Chicago, IL",
    role: "Entrepreneur",
    startupCount: 1,
  },
  {
    id: "40",
    name: "Donald Rivera",
    photo: "/images/person4.jpg",
    rating: 5.0,
    badges: ["Accelerator", "Tech"],
    bio: "Accelerator partner helping startups in emerging tech industries.",
    address: "Singapore",
    role: "Investor",
    totalInvestment: "$38.9M",
  }
]

interface Entrepreneur {
  id: string
  name: string
  avatar: string
  rating: number
}

export interface Startup {
  id: string
  title: string
  logo: string
  description: string
  location: string
  stage: string
  badges: string[]
  entrepreneur: Entrepreneur
  investedAmount: number
  requiredInvestment: number
  slug: string
}

export const DUMMY_SAVED: Startup[] = [
  {
    id: "1",
    title: "EcoTech Solutions",
    logo: "/images/Portfolio1.png",
    description:
      "EcoTech Solutions is pioneering the next generation of sustainable energy infrastructure through advanced AI-powered solar panel technology. Our innovative approach combines machine learning algorithms with cutting-edge photovoltaic systems to maximize energy efficiency and reduce environmental impact across residential and commercial applications.",
    location: "San Francisco, CA",
    stage: "Series A",
    badges: ["CleanTech", "AI", "Energy"],
    entrepreneur: {
      id: "e1",
      name: "Sarah Chen",
      avatar: "/images/person1.jpg",
      rating: 4.8,
    },
    investedAmount: 2500000,
    requiredInvestment: 5000000,
    slug: "ecotech-solutions",
  },
  {
    id: "2",
    title: "HealthAI",
    logo: "/images/Portfolio2.png",
    description:
      "HealthAI is transforming healthcare delivery through artificial intelligence and machine learning technologies. Our platform provides personalized diagnostic solutions, predictive health analytics, and treatment recommendations that empower healthcare providers to deliver more accurate and efficient patient care.",
    location: "Boston, MA",
    stage: "Seed",
    badges: ["HealthTech", "AI", "Diagnostics"],
    entrepreneur: {
      id: "e2",
      name: "Dr. Michael Rodriguez",
      avatar: "/images/person1.jpg",
      rating: 4.9,
    },
    investedAmount: 800000,
    requiredInvestment: 2000000,
    slug: "healthai",
  }
];

export const DUMMY_STARTUPS: Startup[] = [
  {
    id: "1",
    title: "EcoTech Solutions",
    logo: "/images/Portfolio1.png",
    description:
      "EcoTech Solutions is pioneering the next generation of sustainable energy infrastructure through advanced AI-powered solar panel technology. Our innovative approach combines machine learning algorithms with cutting-edge photovoltaic systems to maximize energy efficiency and reduce environmental impact across residential and commercial applications.",
    location: "San Francisco, CA",
    stage: "Series A",
    badges: ["CleanTech", "AI", "Energy"],
    entrepreneur: {
      id: "e1",
      name: "Sarah Chen",
      avatar: "/images/person1.jpg",
      rating: 4.8,
    },
    investedAmount: 2500000,
    requiredInvestment: 5000000,
    slug: "ecotech-solutions",
  },
  {
    id: "2",
    title: "HealthAI",
    logo: "/images/Portfolio2.png",
    description:
      "HealthAI is transforming healthcare delivery through artificial intelligence and machine learning technologies. Our platform provides personalized diagnostic solutions, predictive health analytics, and treatment recommendations that empower healthcare providers to deliver more accurate and efficient patient care.",
    location: "Boston, MA",
    stage: "Seed",
    badges: ["HealthTech", "AI", "Diagnostics"],
    entrepreneur: {
      id: "e2",
      name: "Dr. Michael Rodriguez",
      avatar: "/images/person1.jpg",
      rating: 4.9,
    },
    investedAmount: 800000,
    requiredInvestment: 2000000,
    slug: "healthai",
  },
  {
    id: "3",
    title: "FoodieConnect",
    logo: "/images/Portfolio1.png",
    description:
      "FoodieConnect is revolutionizing the food supply chain by creating direct connections between local farmers and restaurants through blockchain technology. Our platform ensures transparency, fair pricing, and sustainable sourcing while reducing food waste and supporting local agricultural communities.",
    location: "Austin, TX",
    stage: "Pre-Seed",
    badges: ["FoodTech", "Blockchain", "Supply Chain"],
    entrepreneur: {
      id: "e3",
      name: "Emma Thompson",
      avatar: "/images/person1.jpg",
      rating: 4.6,
    },
    investedAmount: 150000,
    requiredInvestment: 500000,
    slug: "foodie-connect",
  },
  {
    id: "4",
    title: "FinanceFlow",
    logo: "/images/Portfolio1.png",
    description:
      "FinanceFlow provides comprehensive automated financial planning and management solutions specifically designed for small and medium-sized businesses. Our SaaS platform integrates with existing accounting systems to provide real-time financial insights, cash flow forecasting, and strategic planning tools.",
    location: "New York, NY",
    stage: "Series A",
    badges: ["FinTech", "SaaS", "Analytics"],
    entrepreneur: {
      id: "e4",
      name: "James Park",
      avatar: "/images/person1.jpg",
      rating: 4.7,
    },
    investedAmount: 3200000,
    requiredInvestment: 8000000,
    slug: "finance-flow",
  },
  {
    id: "5",
    title: "EduVerse",
    logo: "/images/Portfolio2.png",
    description:
      "EduVerse is creating immersive educational experiences through virtual and augmented reality technologies. Our platform enables students and professionals to learn complex subjects through interactive 3D environments, simulations, and collaborative virtual spaces that enhance engagement and retention.",
    location: "Seattle, WA",
    stage: "Seed",
    badges: ["EdTech", "VR", "Learning"],
    entrepreneur: {
      id: "e5",
      name: "Lisa Wang",
      avatar: "/images/person1.jpg",
      rating: 4.5,
    },
    investedAmount: 1200000,
    requiredInvestment: 3000000,
    slug: "eduverse",
  },
  {
    id: "6",
    title: "GreenLogistics",
    logo: "/images/Portfolio1.png",
    description:
      "GreenLogistics is pioneering carbon-neutral delivery solutions for the e-commerce industry. Our innovative logistics network combines electric vehicles, optimized routing algorithms, and sustainable packaging to provide environmentally responsible shipping options for businesses and consumers.",
    location: "Los Angeles, CA",
    stage: "Series B",
    badges: ["Logistics", "GreenTech", "E-commerce"],
    entrepreneur: {
      id: "e6",
      name: "Alex Kumar",
      avatar: "/images/person1.jpg",
      rating: 4.8,
    },
    investedAmount: 5500000,
    requiredInvestment: 12000000,
    slug: "green-logistics",
  },
  {
    id: "7",
    title: "CyberShield",
    logo: "/images/Portfolio1.png",
    description:
      "CyberShield develops next-generation cybersecurity solutions specifically designed for Internet of Things (IoT) devices and networks. Our comprehensive security platform provides real-time threat detection, automated response systems, and advanced encryption protocols to protect connected devices from cyber attacks.",
    location: "Washington, DC",
    stage: "Series A",
    badges: ["CyberSecurity", "IoT", "Enterprise"],
    entrepreneur: {
      id: "e7",
      name: "Rachel Foster",
      avatar: "/images/person1.jpg",
      rating: 4.9,
    },
    investedAmount: 4100000,
    requiredInvestment: 10000000,
    slug: "cyber-shield",
  },
  {
    id: "8",
    title: "AgroBot",
    logo: "/images/Portfolio1.png",
    description:
      "AgroBot is revolutionizing agriculture through autonomous farming robots and precision agriculture technologies. Our intelligent robotic systems can plant, monitor, and harvest crops with unprecedented accuracy, helping farmers increase yields while reducing labor costs and environmental impact.",
    location: "Denver, CO",
    stage: "Seed",
    badges: ["AgriTech", "Robotics", "Automation"],
    entrepreneur: {
      id: "e8",
      name: "David Martinez",
      avatar: "/images/person1.jpg",
      rating: 4.4,
    },
    investedAmount: 900000,
    requiredInvestment: 2500000,
    slug: "agrobot",
  },
  {
    id: "9",
    title: "SpaceComm",
    logo: "/images/Portfolio1.png",
    description:
      "SpaceComm is developing satellite-based internet infrastructure to provide high-speed connectivity to remote and underserved areas worldwide. Our constellation of low-earth orbit satellites delivers reliable internet access to regions where traditional infrastructure is not feasible or cost-effective.",
    location: "Houston, TX",
    stage: "Series A",
    badges: ["SpaceTech", "Telecom", "Infrastructure"],
    entrepreneur: {
      id: "e9",
      name: "Sophie Anderson",
      avatar: "/images/person1.jpg",
      rating: 4.7,
    },
    investedAmount: 6800000,
    requiredInvestment: 15000000,
    slug: "space-comm",
  },
  {
    id: "10",
    title: "MindfulAI",
    logo: "/images/Portfolio1.png",
    description:
      "MindfulAI is creating AI-powered mental health support platforms that provide personalized therapy, mood tracking, and wellness coaching. Our technology combines natural language processing with evidence-based therapeutic approaches to make mental health care more accessible and effective.",
    location: "Portland, OR",
    stage: "Pre-Seed",
    badges: ["MentalHealth", "AI", "Wellness"],
    entrepreneur: {
      id: "e10",
      name: "Dr. Kevin Lee",
      avatar: "/images/person1.jpg",
      rating: 4.6,
    },
    investedAmount: 250000,
    requiredInvestment: 750000,
    slug: "mindful-ai",
  },
  {
    id: "11",
    title: "CleanWater Tech",
    logo: "/images/Portfolio1.png",
    description:
      "CleanWater Tech develops advanced water purification and treatment systems for communities in developing countries. Our innovative filtration technology removes contaminants and pathogens while being cost-effective and easy to maintain, providing access to clean drinking water for underserved populations.",
    location: "Miami, FL",
    stage: "Seed",
    badges: ["WaterTech", "Social Impact", "Hardware"],
    entrepreneur: {
      id: "e11",
      name: "Maria Santos",
      avatar: "/images/person1.jpg",
      rating: 4.8,
    },
    investedAmount: 1800000,
    requiredInvestment: 4000000,
    slug: "clean-water-tech",
  },
  {
    id: "12",
    title: "RetailVision",
    logo: "/images/Portfolio1.png",
    description:
      "RetailVision provides computer vision and analytics solutions for retail optimization. Our AI-powered platform analyzes customer behavior, inventory management, and store operations to help retailers improve sales performance, reduce theft, and enhance the overall shopping experience.",
    location: "Chicago, IL",
    stage: "Series A",
    badges: ["RetailTech", "Computer Vision", "Analytics"],
    entrepreneur: {
      id: "e12",
      name: "Tom Wilson",
      avatar: "/images/person1.jpg",
      rating: 4.5,
    },
    investedAmount: 3800000,
    requiredInvestment: 9000000,
    slug: "retail-vision",
  },
]


// Dummy data for entrepreneur campaigns (expanded for pagination)
export const allCampaigns = [
  {
    id: "STARTUP001",
    title: "EcoTech Smart Water Bottles",
    logo: "/images/Portfolio22.png",
    description:
      "Revolutionary smart water bottles that track hydration and reduce plastic waste through innovative IoT technology.",
    targetAmount: 15000,
    amountRaised: 8750,
    minimumFunding: 100,
    endDate: "2024-07-31",
    status: "Active",
    backers: 87,
  },
  {
    id: "STARTUP002",
    title: "AI-Powered Learning Platform",
    logo: "/images/Portfolio22.png",
    description:
      "Personalized education platform using machine learning to adapt to individual student learning patterns.",
    targetAmount: 25000,
    amountRaised: 22100,
    minimumFunding: 50,
    endDate: "2024-06-15",
    status: "Active",
    backers: 156,
  },
  {
    id: "STARTUP003",
    title: "Sustainable Fashion Marketplace",
    logo: "/images/Portfolio22.png",
    description: "Connecting eco-conscious consumers with sustainable fashion brands and second-hand luxury items.",
    targetAmount: 10000,
    amountRaised: 10000,
    minimumFunding: 25,
    endDate: "2024-05-20",
    status: "Ended",
    backers: 203,
  },
  {
    id: "STARTUP004",
    title: "Urban Farming Solutions",
    logo: "/images/Portfolio22.png",
    description: "Vertical farming kits for urban apartments, making fresh produce accessible in city environments.",
    targetAmount: 8000,
    amountRaised: 3200,
    minimumFunding: 75,
    endDate: "2024-08-10",
    status: "Active",
    backers: 42,
  },
  {
    id: "STARTUP005",
    title: "Smart Home Automation Hub",
    logo: "/images/Portfolio22.png",
    description:
      "Centralized control system for all smart home devices with AI-powered automation and energy optimization.",
    targetAmount: 12000,
    amountRaised: 7800,
    minimumFunding: 60,
    endDate: "2024-08-20",
    status: "Active",
    backers: 95,
  },
  {
    id: "STARTUP006",
    title: "Digital Health Tracker",
    logo: "/images/Portfolio22.png",
    description:
      "Comprehensive health monitoring platform with wearable integration and personalized wellness insights.",
    targetAmount: 18000,
    amountRaised: 15600,
    minimumFunding: 80,
    endDate: "2024-07-15",
    status: "Active",
    backers: 134,
  },
  {
    id: "STARTUP007",
    title: "Renewable Energy Generator",
    logo: "/images/Portfolio22.png",
    description:
      "Portable renewable energy generator for outdoor activities and emergency situations with high efficiency.",
    targetAmount: 30000,
    amountRaised: 12400,
    minimumFunding: 150,
    endDate: "2024-09-05",
    status: "Active",
    backers: 82,
  },
  {
    id: "STARTUP008",
    title: "Biodegradable Packaging",
    logo: "/images/Portfolio22.png",
    description:
      "Innovative biodegradable packaging solutions for e-commerce and food delivery with zero environmental impact.",
    targetAmount: 20000,
    amountRaised: 16800,
    minimumFunding: 100,
    endDate: "2024-08-25",
    status: "Active",
    backers: 168,
  },
]

// Dummy data for explore campaigns
const allCampaignsTable = [
  {
    id: "CAMP001",
    title: "EcoTech Smart Water Bottles",
    logo: "/images/Portfolio2.png",
    description:
      "Revolutionary smart water bottles that track hydration and reduce plastic waste through innovative IoT technology.",
    targetAmount: 15000,
    amountRaised: 8750,
    minimumFunding: 100,
    endDate: "2024-07-31",
    status: "Active",
    backers: 287,
    categories: ["Sustainability", "IoT"],
    founderName: "Sarah Chen",
    founderAvatar: "/images/Portfolio22.png",
    founderRating: 4.8,
  },
  {
    id: "CAMP002",
    title: "AI-Powered Learning Platform",
    logo: "/images/Portfolio2.png",
    description:
      "Personalized education platform using machine learning to adapt to individual student learning patterns.",
    targetAmount: 25000,
    amountRaised: 22100,
    minimumFunding: 50,
    endDate: "2024-06-15",
    status: "Active",
    backers: 356,
    categories: ["Education", "AI"],
    founderName: "Dr. Michael Rodriguez",
    founderAvatar: "/images/Portfolio22.png",
    founderRating: 4.9,
  },
  {
    id: "CAMP003",
    title: "Sustainable Fashion Marketplace",
    logo: "/images/Portfolio2.png",
    description: "Connecting eco-conscious consumers with sustainable fashion brands and second-hand luxury items.",
    targetAmount: 10000,
    amountRaised: 10000,
    minimumFunding: 25,
    endDate: "2024-05-20",
    status: "Ended",
    backers: 203,
    categories: ["Fashion", "Sustainability"],
    founderName: "Alex Thompson",
    founderAvatar: "/images/Portfolio22.png",
    founderRating: 4.7,
  },
  {
    id: "CAMP004",
    title: "Urban Farming Solutions",
    logo: "/images/Portfolio2.png",
    description: "Vertical farming kits for urban apartments, making fresh produce accessible in city environments.",
    targetAmount: 8000,
    amountRaised: 3200,
    minimumFunding: 75,
    endDate: "2024-08-10",
    status: "Active",
    backers: 42,
    categories: ["Agriculture", "Technology"],
    founderName: "Emma Wilson",
    founderAvatar: "/images/Portfolio22.png",
    founderRating: 4.6,
  },
  {
    id: "CAMP005",
    title: "Green Energy Storage Solutions",
    logo: "/images/Portfolio2.png",
    description:
      "Next-generation battery technology for renewable energy storage in residential and commercial applications.",
    targetAmount: 50000,
    amountRaised: 35000,
    minimumFunding: 200,
    endDate: "2024-08-15",
    status: "Active",
    backers: 175,
    categories: ["Energy", "Technology"],
    founderName: "James Park",
    founderAvatar: "/images/Portfolio22.png",
    founderRating: 4.5,
  },
  {
    id: "CAMP006",
    title: "Mental Health AI Assistant",
    logo: "/images/Portfolio2.png",
    description:
      "AI-powered mental health support platform providing 24/7 personalized guidance and therapy resources.",
    targetAmount: 30000,
    amountRaised: 28500,
    minimumFunding: 100,
    endDate: "2024-07-20",
    status: "Active",
    backers: 285,
    categories: ["Healthcare", "AI"],
    founderName: "Dr. Lisa Johnson",
    founderAvatar: "/images/Portfolio22.png",
    founderRating: 4.9,
  },
  {
    id: "CAMP007",
    title: "Blockchain Supply Chain Tracker",
    logo: "/images/Portfolio2.png",
    description:
      "Transparent supply chain management using blockchain technology for food safety and authenticity verification.",
    targetAmount: 20000,
    amountRaised: 20000,
    minimumFunding: 150,
    endDate: "2024-05-30",
    status: "Ended",
    backers: 133,
    categories: ["Technology", "Supply Chain"],
    founderName: "Robert Chen",
    founderAvatar: "/images/Portfolio22.png",
    founderRating: 4.7,
  },
  {
    id: "CAMP008",
    title: "AR Learning Tools for Kids",
    logo: "/images/Portfolio2.png",
    description:
      "Augmented reality educational tools that make learning interactive and engaging for children aged 6-12.",
    targetAmount: 18000,
    amountRaised: 12600,
    minimumFunding: 75,
    endDate: "2024-09-01",
    status: "Active",
    backers: 168,
    categories: ["Education", "AR"],
    founderName: "Maria Garcia",
    founderAvatar: "/images/Portfolio22.png",
    founderRating: 4.6,
  },
  {
    id: "CAMP009",
    title: "Smart Home Security System",
    logo: "/images/Portfolio2.png",
    description:
      "AI-powered home security with facial recognition, smart alerts, and integration with existing smart home devices.",
    targetAmount: 40000,
    amountRaised: 31200,
    minimumFunding: 250,
    endDate: "2024-08-25",
    status: "Active",
    backers: 124,
    categories: ["Technology", "Security"],
    founderName: "David Kim",
    founderAvatar: "/images/Portfolio22.png",
    founderRating: 4.5,
  },
  {
    id: "CAMP010",
    title: "Sustainable Food Delivery",
    logo: "/images/Portfolio2.png",
    description: "Eco-friendly food delivery service using electric vehicles and biodegradable packaging solutions.",
    targetAmount: 22000,
    amountRaised: 18700,
    minimumFunding: 120,
    endDate: "2024-08-30",
    status: "Active",
    backers: 156,
    categories: ["Sustainability", "Food"],
    founderName: "Sophia Martinez",
    founderAvatar: "/images/Portfolio22.png",
    founderRating: 4.4,
  },
  {
    id: "CAMP011",
    title: "Wearable Health Monitor",
    logo: "/images/Portfolio2.png",
    description:
      "Advanced health monitoring wearable that tracks vital signs and provides early warning for potential health issues.",
    targetAmount: 35000,
    amountRaised: 27500,
    minimumFunding: 180,
    endDate: "2024-09-15",
    status: "Active",
    backers: 210,
    categories: ["Healthcare", "Wearable"],
    founderName: "Dr. Thomas Lee",
    founderAvatar: "/images/Portfolio22.png",
    founderRating: 4.8,
  },
  {
    id: "CAMP012",
    title: "Community Solar Initiative",
    logo: "/images/Portfolio2.png",
    description:
      "Neighborhood-based solar power sharing platform that reduces energy costs and carbon footprint for communities.",
    targetAmount: 45000,
    amountRaised: 32000,
    minimumFunding: 200,
    endDate: "2024-10-01",
    status: "Active",
    backers: 178,
    categories: ["Energy", "Community"],
    founderName: "Olivia Johnson",
    founderAvatar: "/images/Portfolio22.png",
    founderRating: 4.7,
  },
]

export const CROWDFUNDING_TOTAL = "12,345.78"; // Dummy data for Crowdfunding
export const INVEST_TOTAL = "2,050.50"; // Dummy data for Invest
export const MVP_TOTAL = "19";
export const SEED_TOTAL = "23";
export const FINAL_TOTAL = "17";